version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: dhanya00
      MYSQL_DATABASE: todolist
    volumes:
      - mysql-data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-u", "root", -h", "localhost"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - db
        # condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: dhanya00
      MYSQL_DATABASE: todolist
    volumes:
      - .:/app
    command: ["python", "app.py"]

volumes:
  mysql-data:
